#!/usr/bin/env python3
import requests

def download(url):
    r = requests.get(url)
    return r.text

with open('linpeas.sh', 'w') as l:
    l.write(download('https://github.com/carlospolop/PEASS-ng/releases/latest/download/linpeas.sh'))