#!/usr/bin/env python3
import os

path = '/opt/git/PEASS-ng/winPEAS/winPEASbat'
itemPath = f'{path}/winPEAS.bat'
cdir = os.getcwd()

os.chdir(path)
os.system('git pull')

os.system(f'cp {itemPath} {cdir}')